### ISSUE TITLE
DOESN'T BUILD!!!!

### ISSUE THREAD

**Issue by jpike88** [forcedotcom/DeskApiClient-Java#61]
Why would you pull in the beta of a repo and not think that was going to break??

<dependency>
            <groupId>com.squareup.okhttp</groupId>
            <artifactId>okhttp-urlconnection</artifactId>
            <version>2.6.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp</groupId>
            <artifactId>okhttp</artifactId>
            <version>2.6.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.squareup.retrofit</groupId>
            <artifactId>retrofit</artifactId>
            <version>2.0.0-beta2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.squareup.retrofit</groupId>
            <artifactId>converter-gson</artifactId>
            <version>2.0.0-beta2</version>
            <scope>compile</scope>
        </dependency>

**Comment by mattkranzler5** [comment]
Hey @jpike88 we will be releasing 1.3.0 very shortly which will address this issue. I apologize for the inconvenience!

**Comment by jerrellmardis** [comment]
Fixed in #65
